name: Build and Test
on:
    push:
        branches:
            - main
            # Optionally, you can specify other branches or tags to trigger the workflow
jobs:
  # This job will run on the latest version of Ubuntu and will perform the following steps:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x' # Use the latest LTS Node.js version for better compatibility

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            # Optionally, you can add more steps for building, linting, or deploying your application