on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - testing
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy application
        env:
          ENV: ${{ github.event.inputs.environment }}
        run: echo "Deploying to $ENV"
